// Datos mock centralizados para toda la aplicación

// Usuarios mock
export const mockUsers = [
  {
    id: "1",
    name: "Juan Pérez",
    email: "juan.perez@email.com",
    phone: "987654321",
    profilePicture: null,
    isActive: true,
    createdAt: "2024-01-15T10:30:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "2",
    name: "María García",
    email: "maria.garcia@email.com",
    phone: "987654322",
    profilePicture: null,
    isActive: true,
    createdAt: "2024-01-10T09:20:00Z",
    updatedAt: "2024-01-10T09:20:00Z",
  },
];

// Categorías mock
export const mockCategories = [
  {
    id: "1",
    name: "Documentos",
    iconName: "document-text",
    color: "#4b7bec",
    isActive: true,
  },
  {
    id: "2",
    name: "Vivienda",
    iconName: "home",
    color: "#2ecc71",
    isActive: true,
  },
  {
    id: "3",
    name: "Vehículos",
    iconName: "car",
    color: "#e74c3c",
    isActive: true,
  },
  {
    id: "4",
    name: "Educación",
    iconName: "school",
    color: "#f39c12",
    isActive: true,
  },
  {
    id: "5",
    name: "Empresas",
    iconName: "business",
    color: "#9b59b6",
    isActive: true,
  },
  {
    id: "6",
    name: "Salud",
    iconName: "medkit",
    color: "#3498db",
    isActive: true,
  },
  {
    id: "7",
    name: "Identidad",
    iconName: "people",
    color: "#e67e22",
    isActive: true,
  },
  {
    id: "8",
    name: "Impuestos",
    iconName: "card",
    color: "#16a085",
    isActive: true,
  },
];

// Empresas/Agencias mock
export const mockEnterprises = [
  {
    id: "1",
    name: "Banco de Crédito del Perú",
    shortName: "BCP",
    type: "Entidad bancaria",
    logo: require("../assets/default-logo.png"),
    address: "Av. Independencia 123, Arequipa",
    schedule: "Lun - Vie: 9:00 - 18:00, Sáb: 9:00 - 13:00",
    phone: "+51 954 123 456",
    isActive: true,
    activeQueues: 4,
    tenantId: "tenant1",
    settings: {},
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "2",
    name: "RENIEC",
    shortName: "RENIEC",
    type: "Entidad gubernamental",
    logo: require("../assets/default-logo.png"),
    address: "Av. Dolores Prolongación 456, Arequipa",
    schedule: "Lun - Vie: 8:00 - 17:00",
    phone: "+51 954 789 123",
    isActive: true,
    activeQueues: 3,
    tenantId: "tenant2",
    settings: {},
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "3",
    name: "SUNAT",
    shortName: "SUNAT",
    type: "Entidad tributaria",
    logo: require("../assets/default-logo.png"),
    address: "Jr. Comercio 789, Cercado de Arequipa",
    schedule: "Lun - Vie: 8:30 - 17:30",
    phone: "+51 954 456 789",
    isActive: true,
    activeQueues: 2,
    tenantId: "tenant3",
    settings: {},
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "4",
    name: "Hospital Regional",
    shortName: "Hospital",
    type: "Centro de salud",
    logo: require("../assets/default-logo.png"),
    address: "Av. Alcides Carrión 321, Arequipa",
    schedule: "24 horas",
    phone: "+51 954 321 654",
    isActive: true,
    activeQueues: 5,
    tenantId: "tenant4",
    settings: {},
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },
];

// Colas mock por empresa
export const mockQueuesByEnterprise = {
  1: [
    // BCP
    {
      id: "q1",
      name: "Operaciones en ventanilla",
      description: "Depósitos, retiros y transferencias",
      icon: "cash-outline",
      category: "Bancario",
      priority: "high",
      peopleWaiting: 12,
      avgTime: "15 min",
      averageWaitTime: 900, // en segundos
      enterpriseId: "1",
      tenantId: "tenant1",
      isActive: true,
      totalProcessedToday: 45,
      createdAt: "2024-01-15T08:00:00Z",
      updatedAt: "2024-01-15T10:30:00Z",
    },
    {
      id: "q2",
      name: "Atención al cliente",
      description: "Consultas y reclamos",
      icon: "people-outline",
      category: "Servicio",
      priority: "medium",
      peopleWaiting: 8,
      avgTime: "20 min",
      averageWaitTime: 1200,
      enterpriseId: "1",
      tenantId: "tenant1",
      isActive: true,
      totalProcessedToday: 32,
      createdAt: "2024-01-15T08:00:00Z",
      updatedAt: "2024-01-15T10:30:00Z",
    },
    {
      id: "q3",
      name: "Apertura de cuentas",
      description: "Nuevas cuentas y productos",
      icon: "document-text-outline",
      category: "Productos",
      priority: "medium",
      peopleWaiting: 5,
      avgTime: "25 min",
      averageWaitTime: 1500,
      enterpriseId: "1",
      tenantId: "tenant1",
      isActive: true,
      totalProcessedToday: 18,
      createdAt: "2024-01-15T08:00:00Z",
      updatedAt: "2024-01-15T10:30:00Z",
    },
    {
      id: "q4",
      name: "Préstamos y créditos",
      description: "Solicitudes de crédito",
      icon: "card-outline",
      category: "Créditos",
      priority: "low",
      peopleWaiting: 3,
      avgTime: "30 min",
      averageWaitTime: 1800,
      enterpriseId: "1",
      tenantId: "tenant1",
      isActive: true,
      totalProcessedToday: 12,
      createdAt: "2024-01-15T08:00:00Z",
      updatedAt: "2024-01-15T10:30:00Z",
    },
  ],
  2: [
    // RENIEC
    {
      id: "q5",
      name: "Trámites de DNI",
      description: "Emisión y renovación de DNI",
      icon: "card-outline",
      category: "Identidad",
      priority: "high",
      peopleWaiting: 20,
      avgTime: "35 min",
      averageWaitTime: 2100,
      enterpriseId: "2",
      tenantId: "tenant2",
      isActive: true,
      totalProcessedToday: 67,
      createdAt: "2024-01-15T08:00:00Z",
      updatedAt: "2024-01-15T10:30:00Z",
    },
    {
      id: "q6",
      name: "Pasaportes",
      description: "Emisión de pasaportes",
      icon: "airplane-outline",
      category: "Documentos",
      priority: "medium",
      peopleWaiting: 15,
      avgTime: "25 min",
      averageWaitTime: 1500,
      enterpriseId: "2",
      tenantId: "tenant2",
      isActive: true,
      totalProcessedToday: 23,
      createdAt: "2024-01-15T08:00:00Z",
      updatedAt: "2024-01-15T10:30:00Z",
    },
    {
      id: "q7",
      name: "Certificados",
      description: "Certificados de nacimiento, defunción",
      icon: "document-outline",
      category: "Certificados",
      priority: "low",
      peopleWaiting: 8,
      avgTime: "20 min",
      averageWaitTime: 1200,
      enterpriseId: "2",
      tenantId: "tenant2",
      isActive: true,
      totalProcessedToday: 34,
      createdAt: "2024-01-15T08:00:00Z",
      updatedAt: "2024-01-15T10:30:00Z",
    },
  ],
  3: [
    // SUNAT
    {
      id: "q8",
      name: "Declaraciones",
      description: "Presentación de declaraciones",
      icon: "document-text-outline",
      category: "Tributario",
      priority: "high",
      peopleWaiting: 18,
      avgTime: "40 min",
      averageWaitTime: 2400,
      enterpriseId: "3",
      tenantId: "tenant3",
      isActive: true,
      totalProcessedToday: 29,
      createdAt: "2024-01-15T08:00:00Z",
      updatedAt: "2024-01-15T10:30:00Z",
    },
    {
      id: "q9",
      name: "RUC y comprobantes",
      description: "Trámites de RUC",
      icon: "business-outline",
      category: "Empresarial",
      priority: "medium",
      peopleWaiting: 10,
      avgTime: "30 min",
      averageWaitTime: 1800,
      enterpriseId: "3",
      tenantId: "tenant3",
      isActive: true,
      totalProcessedToday: 19,
      createdAt: "2024-01-15T08:00:00Z",
      updatedAt: "2024-01-15T10:30:00Z",
    },
  ],
  4: [
    // Hospital
    {
      id: "q10",
      name: "Consulta externa",
      description: "Citas médicas generales",
      icon: "medkit-outline",
      category: "Salud",
      priority: "high",
      peopleWaiting: 25,
      avgTime: "45 min",
      averageWaitTime: 2700,
      enterpriseId: "4",
      tenantId: "tenant4",
      isActive: true,
      totalProcessedToday: 89,
      createdAt: "2024-01-15T08:00:00Z",
      updatedAt: "2024-01-15T10:30:00Z",
    },
    {
      id: "q11",
      name: "Emergencias",
      description: "Atención de emergencias",
      icon: "medical-outline",
      category: "Urgencias",
      priority: "high",
      peopleWaiting: 5,
      avgTime: "60 min",
      averageWaitTime: 3600,
      enterpriseId: "4",
      tenantId: "tenant4",
      isActive: true,
      totalProcessedToday: 34,
      createdAt: "2024-01-15T08:00:00Z",
      updatedAt: "2024-01-15T10:30:00Z",
    },
    {
      id: "q12",
      name: "Laboratorio",
      description: "Análisis y exámenes",
      icon: "flask-outline",
      category: "Diagnóstico",
      priority: "medium",
      peopleWaiting: 12,
      avgTime: "30 min",
      averageWaitTime: 1800,
      enterpriseId: "4",
      tenantId: "tenant4",
      isActive: true,
      totalProcessedToday: 56,
      createdAt: "2024-01-15T08:00:00Z",
      updatedAt: "2024-01-15T10:30:00Z",
    },
    {
      id: "q13",
      name: "Farmacia",
      description: "Retiro de medicamentos",
      icon: "medical-outline",
      category: "Medicamentos",
      priority: "low",
      peopleWaiting: 7,
      avgTime: "15 min",
      averageWaitTime: 900,
      enterpriseId: "4",
      tenantId: "tenant4",
      isActive: true,
      totalProcessedToday: 78,
      createdAt: "2024-01-15T08:00:00Z",
      updatedAt: "2024-01-15T10:30:00Z",
    },
    {
      id: "q14",
      name: "Admisión",
      description: "Registro y documentación",
      icon: "clipboard-outline",
      category: "Administrativa",
      priority: "medium",
      peopleWaiting: 15,
      avgTime: "20 min",
      averageWaitTime: 1200,
      enterpriseId: "4",
      tenantId: "tenant4",
      isActive: true,
      totalProcessedToday: 45,
      createdAt: "2024-01-15T08:00:00Z",
      updatedAt: "2024-01-15T10:30:00Z",
    },
  ],
};

// Tickets mock
export const mockTickets = [
  {
    id: "t1",
    number: "A001",
    queueId: "q1",
    enterpriseId: "1",
    enterpriseName: "Banco de Crédito del Perú",
    queueName: "Operaciones en ventanilla",
    customerName: "Juan Pérez",
    customerPhone: "987654321",
    customerEmail: "juan.perez@email.com",
    serviceType: "Depósito",
    priority: "normal",
    status: "waiting",
    position: 3,
    estimatedWaitTime: 900,
    actualWaitTime: 0,
    serviceTime: 0,
    createdAt: "2024-01-15T10:30:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
    calledAt: null,
    completedAt: null,
    cancelledAt: null,
    skippedAt: null,
    notes: "",
    reason: "",
  },
  {
    id: "t2",
    number: "B015",
    queueId: "q5",
    enterpriseId: "2",
    enterpriseName: "RENIEC",
    queueName: "Trámites de DNI",
    customerName: "María García",
    customerPhone: "987654322",
    customerEmail: "maria.garcia@email.com",
    serviceType: "Renovación DNI",
    priority: "normal",
    status: "waiting",
    position: 8,
    estimatedWaitTime: 1680,
    actualWaitTime: 0,
    serviceTime: 0,
    createdAt: "2024-01-15T09:45:00Z",
    updatedAt: "2024-01-15T09:45:00Z",
    calledAt: null,
    completedAt: null,
    cancelledAt: null,
    skippedAt: null,
    notes: "",
    reason: "",
  },
];

// Función helper para generar IDs únicos
export const generateId = () => {
  return Math.random().toString(36).substr(2, 9);
};

// Función helper para generar números de ticket
export const generateTicketNumber = (queueId) => {
  const prefixes = {
    q1: "A",
    q2: "B",
    q3: "C",
    q4: "D",
    q5: "E",
    q6: "F",
    q7: "G",
    q8: "H",
    q9: "I",
    q10: "J",
    q11: "K",
    q12: "L",
    q13: "M",
    q14: "N",
  };

  const prefix = prefixes[queueId] || "X";
  const number = Math.floor(Math.random() * 999) + 1;
  return `${prefix}${number.toString().padStart(3, "0")}`;
};

// Función para simular errores de red ocasionales
export const shouldSimulateError = (errorRate = 0.1) => {
  return Math.random() < errorRate;
};

// Función para buscar en arrays
export const searchInArray = (array, searchText, fields = ["name"]) => {
  if (!searchText.trim()) return array;

  const search = searchText.toLowerCase();
  return array.filter((item) =>
    fields.some(
      (field) => item[field] && item[field].toLowerCase().includes(search)
    )
  );
};
